// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ProductAPI.Models;

public partial class Client
{
    public int ClientId { get; set; }

    public string ClientName { get; set; }

    public string ClientEmail { get; set; }

    public string ClientAddress { get; set; }

    public string ClientPhone { get; set; }

    public int LocationId { get; set; }

    public string UserId { get; set; }

    public virtual Location Location { get; set; }

    public virtual ICollection<RentedProduct> RentedProduct { get; set; } = new List<RentedProduct>();
}