// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ProductAPI.Models;

public partial class Employee
{
    public int EmployeeId { get; set; }

    public string EmployeeName { get; set; }

    public string EmployeeRole { get; set; }

    public string UserId { get; set; }

    public virtual ICollection<RentedProduct> RentedProduct { get; set; } = new List<RentedProduct>();

    public virtual AspNetUsers User { get; set; }
}