// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RentBrandOutfit.Models;

public partial class Product
{
    public int ProductId { get; set; }

    public string ProductName { get; set; }

    public string ProductMaterial { get; set; }

    public string ProductColour { get; set; }

    public int ProductQty { get; set; }

    public string ProductImg { get; set; }

    public decimal ProductPrice { get; set; }

    public int CategoryId { get; set; }

    public int BrandId { get; set; }

    public virtual Brand Brand { get; set; }

    public virtual Category Category { get; set; }

    public virtual ICollection<RentedProduct> RentedProduct { get; set; } = new List<RentedProduct>();
}