// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RentBrandOutfit.Models;

public partial class RentedProduct
{
    public int RentId { get; set; }

    public DateTime RentStartDate { get; set; }

    public DateTime RentEndDate { get; set; }

    public int RentQuantity { get; set; }

    public decimal RentTotalPrice { get; set; }

    public int ClientId { get; set; }

    public int ProductId { get; set; }

    public int EmployeeId { get; set; }

    public virtual Client Client { get; set; }

    public virtual Employee Employee { get; set; }

    public virtual Product Product { get; set; }
}